"""Web API adapter (Phase 8): turn an OpenAPI description into a plug.

  python tools/openapi_plug.py api.json OUT_DIR

Reads an OpenAPI 3 description (JSON), and writes a NEW plug folder:
  plug.json   permissions.network = exactly the API's https host, nothing else
  app/        a small page listing the API's GET operations; each one goes out through
              the socket's gateway (net.fetch), so the usual rules apply: declared host
              only, https only, no cookies, logged on the report card.

Read-only on the description; refuses to overwrite an existing folder.
Only GET operations are offered in v0 (reading data is the safe place to start).
"""
import json
import re
import sys
from pathlib import Path
from urllib.parse import urlsplit

sys.path.insert(0, str(Path(__file__).resolve().parent))
import validate  # noqa: E402

PAGE = """<!doctype html>
<meta charset="utf-8">
<title>{title}</title>
<style>
body{{margin:0;padding:14px;background:#13101c;color:#ece8ff;font:14px/1.45 system-ui,sans-serif}}
h1{{font-size:16px;margin:0 0 4px}}p{{color:#9d96bf;margin:0 0 12px}}
.op{{border:1px solid #2c2642;border-radius:10px;padding:10px;margin-bottom:8px}}
.op b{{font:600 12px ui-monospace,Consolas,monospace;color:#7be0ad;margin-right:6px}}
input{{background:#0f0d17;color:#ece8ff;border:1px solid #2c2642;border-radius:6px;padding:3px 6px;margin:4px 4px 0 0}}
button{{background:#ff6fae;border:0;border-radius:6px;padding:4px 10px;font-weight:600;cursor:pointer}}
pre{{white-space:pre-wrap;word-break:break-word;background:#0f0d17;border-radius:8px;padding:8px;max-height:220px;overflow:auto;margin:8px 0 0}}
</style>
<h1>{title}</h1>
<p>Talks only to {host}, through the Work Zone gateway.</p>
<div id="ops"></div>
<script>
// Generated by tools/openapi_plug.py. Every call goes through the socket's gateway (net.fetch).
var BASE = {base};
var OPS = {ops};
var waiting = {{}}, next = 1;
addEventListener('message', function (e) {{
  var m = e.data;
  if (m && m.topic === 'reply' && waiting[m.id]) {{ waiting[m.id](m); delete waiting[m.id]; }}
}});
function call(url, out) {{
  var id = next++;
  out.textContent = 'asking...';
  waiting[id] = function (m) {{
    if (!m.ok) {{ out.textContent = 'refused: ' + m.reason; return; }}
    var r = m.reply || {{}};
    out.textContent = r.status ? ('status ' + r.status + '\\n\\n' + r.body) : 'failed';
  }};
  parent.postMessage({{ topic: 'net.fetch', url: url, id: id }}, '*');
}}
OPS.forEach(function (op) {{
  var box = document.createElement('div'); box.className = 'op';
  var head = document.createElement('div');
  var verb = document.createElement('b'); verb.textContent = 'GET';
  head.appendChild(verb); head.appendChild(document.createTextNode(op.path + (op.summary ? '  ' + op.summary : '')));
  box.appendChild(head);
  var inputs = {{}};
  op.params.forEach(function (p) {{
    var i = document.createElement('input'); i.placeholder = p; inputs[p] = i; box.appendChild(i);
  }});
  var go = document.createElement('button'); go.textContent = 'call';
  var out = document.createElement('pre'); out.hidden = true;
  go.onclick = function () {{
    var path = op.path.replace(/\\{{([^}}]+)\\}}/g, function (_, n) {{ return encodeURIComponent(inputs[n].value || ''); }});
    out.hidden = false; call(BASE + path, out);
  }};
  box.appendChild(go); box.appendChild(out);
  document.getElementById('ops').appendChild(box);
}});
parent.postMessage({{ topic: 'plug.ready' }}, '*');
</script>
"""


def from_spec(spec):
    """Return (manifest, page_html) for an OpenAPI 3 description. Raises ValueError with a plain reason."""
    if not isinstance(spec, dict) or not str(spec.get("openapi", "")).startswith("3"):
        raise ValueError("this doesn't look like an OpenAPI 3 description (no 'openapi: 3.x')")
    servers = spec.get("servers") or []
    if not servers or not isinstance(servers[0], dict) or not servers[0].get("url"):
        raise ValueError("the description has no server address")
    url = servers[0]["url"]
    parts = urlsplit(url)
    if parts.scheme != "https" or not parts.hostname:
        raise ValueError(f"the API must use https (got {url!r})")
    if parts.port or parts.username or parts.password:
        raise ValueError("the API address must not have a port or a login in it")
    host = parts.hostname.lower().rstrip(".")
    if not validate.HOSTNAME.match(host) or re.fullmatch(r"[\d.]+", host):
        raise ValueError(f"{host!r} is not a host name a plug can declare")
    base = f"https://{host}{parts.path.rstrip('/')}"
    ops = []
    for path, item in sorted((spec.get("paths") or {}).items()):
        get = item.get("get") if isinstance(item, dict) else None
        if not isinstance(get, dict) or not isinstance(path, str) or not path.startswith("/"):
            continue
        params = re.findall(r"\{([A-Za-z0-9_]+)\}", path)
        ops.append({"path": path, "summary": str(get.get("summary", ""))[:80], "params": params})
    if not ops:
        raise ValueError("the description has no GET operations to offer")
    info = spec.get("info") or {}
    title = re.sub(r"[^A-Za-z0-9 ._-]+", " ", str(info.get("title") or host)).strip()[:60] or host
    slug = re.sub(r"[^a-z0-9-]+", "-", title.lower()).strip("-") or "api"
    manifest = {
        "plug": "0", "id": f"zone.work.api-{slug}", "name": title, "version": "0.1.0",
        "kind": "service", "entry": "index.html", "views": ["panel"], "hosts": ["any"],
        "permissions": {"network": [host], "ui": "panel"},
        "author_key": "ed25519:" + "0" * 64,
        "description": f"Web API plug for {host}, made from its OpenAPI description. GET operations only.",
    }
    errors = validate.validate(manifest)
    if errors:
        raise ValueError("generated manifest is not valid: " + "; ".join(errors))
    # json.dumps output is safe inside a <script>: escape '<' so nothing can close the tag early.
    js = lambda v: json.dumps(v).replace("<", "\\u003c")  # noqa: E731
    page = PAGE.format(title=title.replace("<", ""), host=host, base=js(base), ops=js(ops))
    return manifest, page


def make(spec_path, out_dir):
    out = Path(out_dir)
    if out.exists():
        raise FileExistsError(f"{out} already exists; pick a new folder")
    spec = json.loads(Path(spec_path).read_text(encoding="utf-8"))
    manifest, page = from_spec(spec)
    (out / "app").mkdir(parents=True)
    (out / "plug.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    (out / "app" / "index.html").write_text(page, encoding="utf-8")
    return out, manifest


def main(argv):
    if len(argv) != 2:
        print(__doc__)
        return 2
    try:
        out, m = make(argv[0], argv[1])
    except (ValueError, FileExistsError, json.JSONDecodeError) as e:
        print(f"Not made: {e}")
        return 1
    print(f"Made {out}: {m['id']} (may only reach {m['permissions']['network'][0]})")
    print(f"Next: python tools/pack.py pack {out} YOUR.key {out.name}.plug --inline")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
